/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import BUS.GiaoVienBUS;
import BUS.LopHocBUS;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;


import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import DTO.LopHoc;
import DTO.GiaoVien;


public class QLGVView extends javax.swing.JFrame {

    /**
     * Creates new form QLGVView
     */
    String dbUrl ="jdbc:mysql://localhost:3306/qlhs";
    String username = "root"; String password= "12345678";
    String imgURL="none";
    File directory = new File("");
    SimpleDateFormat formatDate = new SimpleDateFormat("dd/MM/yyyy");
    ArrayList<GiaoVien> dsgv = new ArrayList<>();
    DefaultTableModel model ;
    public void loadData(){
        try{   
            dsgv.clear();
            GiaoVienBUS gvBUS = new GiaoVienBUS();
            dsgv = gvBUS.getAllGiaoVien();
        } catch(Exception e){
            System.out.println("Connect Error "+e);
        } 
    }
           

    public void loadDataTable(){   
        loadData();
        model = (DefaultTableModel)tbDSGV.getModel();
        model.setRowCount(0);
        for (int i=0;i<dsgv.size();i++){          
            model.addRow(new Object[]{i+1,dsgv.get(i).getMSGV(),dsgv.get(i).getHoTen(),formatDate.format(dsgv.get(i).getNgaySinh()),
                dsgv.get(i).getGioiTinh(),dsgv.get(i).getlop(),dsgv.get(i).getQueQuan()});
          
        }                 
    }
    
    public void loadDataCBLop(){
        LopHocBUS lh = new LopHocBUS();
        ArrayList<LopHoc> arr = new ArrayList<>();
        arr = lh.getAllLopHoc();
        for (LopHoc l : arr){
            cbLop.addItem(l.getTenLop());
        }
        
    }
    public QLGVView() {
        initComponents();
        addBtn.setIcon(new ImageIcon(new ImageIcon("src//images//plus.png").getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
        delBtn.setIcon(new ImageIcon(new ImageIcon("src//images//delete.png").getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
        editBtn.setIcon(new ImageIcon(new ImageIcon("src//images//edit.png").getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
        backBtn.setIcon(new ImageIcon(new ImageIcon("src//images//previous.png").getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
        RefreshMenu.setIcon(new ImageIcon(new ImageIcon("src//images//refresh.png").getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
        searchMenu.setIcon(new ImageIcon(new ImageIcon("src//images//search.png").getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
        this.getContentPane().setBackground(new java.awt.Color(110, 255, 140));
        loadDataCBLop();
        loadDataTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbDSHS = new javax.swing.JTable();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        tfMSGV = new javax.swing.JTextField();
        tfHoTen = new javax.swing.JTextField();
        tfNgaySinh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbNam = new javax.swing.JRadioButton();
        rbNu = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        imgLabel = new javax.swing.JLabel();
        cbQueQuan = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbDSGV = new javax.swing.JTable();
        cbLop = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        RefreshMenu = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        searchMenu = new javax.swing.JMenu();
        TheoTen = new javax.swing.JMenuItem();
        TheoMSGV = new javax.swing.JMenuItem();
        TheoNgaySinh = new javax.swing.JMenuItem();
        TheoGioiTinh = new javax.swing.JMenuItem();
        TheoQueQuan = new javax.swing.JMenuItem();
        TheoLop = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        tbDSHS.setBackground(new java.awt.Color(204, 255, 255));
        tbDSHS.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tbDSHS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "MSHS", "HỌ VÀ TÊN", "NGÀY SINH", "GIỚI TÍNH", "LỚP", "QUÊ QUÁN"
            }
        ));
        tbDSHS.setSelectionBackground(new java.awt.Color(0, 0, 153));
        tbDSHS.setSelectionForeground(new java.awt.Color(255, 255, 51));
        tbDSHS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDSHSMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbDSHS);

        jMenuItem7.setText("jMenuItem7");

        jMenuItem9.setText("jMenuItem9");

        jMenuItem11.setText("jMenuItem11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfMSGV.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        tfHoTen.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tfHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHoTenActionPerformed(evt);
            }
        });

        tfNgaySinh.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tfNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNgaySinhActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("MSGV : ");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Họ và tên : ");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Ngày sinh : ");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Giới tính :");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Lớp :");

        buttonGroup1.add(rbNam);
        rbNam.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbNam.setText("NAM");
        rbNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNamActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbNu);
        rbNu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbNu.setText("NỮ");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Quê quán :");

        addBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addBtn.setText("THÊM");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        delBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        delBtn.setText("XÓA");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        editBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editBtn.setText("SỬA");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        backBtn.setText("QUAY LẠI");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        imgLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Image"));
        imgLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgLabelMouseClicked(evt);
            }
        });

        cbQueQuan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbQueQuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "An Giang", "Bà Rịa – Vũng Tàu", "Bạc Liêu", "Bắc Giang", "Bắc Kạn", "Bắc Ninh", "Bến Tre", "Bình Dương", "Bình Định", "Bình Phước", "Bình Thuận", "Cà Mau", "Cao Bằng", "Cần Thơ", "Đà Nẵng", "Đắk Lắk", "Đắk Nông", "Điện Biên", "Đồng Nai", "Đồng Tháp", "Gia Lai", "Hà Giang", "Hà Nam", "Hà Nội", "Hà Tĩnh", "Hải Dương", "Hải Phòng", "Hậu Giang", "Hòa Bình", "Thành phố Hồ Chí Minh", "Hưng Yên", "Khánh Hòa", "Kiên Giang", "Kon Tum", "Lai Châu", "Lạng Sơn", "Lào Cai", "Lâm Đồng", "Long An", "Nam Định", "Nghệ An", "Ninh Bình", "Ninh Thuận", "Phú Thọ", "Phú Yên", "Quảng Bình", "Quảng Nam", "Quảng Ngãi", "Quảng Ninh", "Quảng Trị", "Sóc Trăng", "Sơn La", "Tây Ninh", "Thái Bình", "Thái Nguyên", "Thanh Hóa", "Thừa Thiên Huế", "Tiền Giang", "Trà Vinh", "Tuyên Quang", "Vĩnh Long", "Vĩnh Phúc", "Yên Bái" }));
        cbQueQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQueQuanActionPerformed(evt);
            }
        });

        tbDSGV.setBackground(new java.awt.Color(204, 255, 255));
        tbDSGV.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tbDSGV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "MSGV", "HỌ VÀ TÊN", "NGÀY SINH", "GIỚI TÍNH", "LỚP", "QUÊ QUÁN"
            }
        ));
        tbDSGV.setSelectionBackground(new java.awt.Color(0, 0, 153));
        tbDSGV.setSelectionForeground(new java.awt.Color(255, 255, 51));
        tbDSGV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDSGVMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbDSGV);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 0));
        jLabel13.setText("QUẢN LÝ GIÁO VIÊN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(277, 277, 277))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Công cụ");

        RefreshMenu.setText("Refresh");
        RefreshMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshMenuActionPerformed(evt);
            }
        });
        jMenu1.add(RefreshMenu);

        jMenuItem5.setText("Lọc");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        searchMenu.setText("Tìm kiếm");

        TheoTen.setText("Theo tên");
        TheoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TheoTenActionPerformed(evt);
            }
        });
        searchMenu.add(TheoTen);

        TheoMSGV.setText("Theo MSGV");
        TheoMSGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TheoMSGVActionPerformed(evt);
            }
        });
        searchMenu.add(TheoMSGV);

        TheoNgaySinh.setText("Theo Ngày sinh");
        TheoNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TheoNgaySinhActionPerformed(evt);
            }
        });
        searchMenu.add(TheoNgaySinh);

        TheoGioiTinh.setText("Theo giới tính");
        TheoGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TheoGioiTinhActionPerformed(evt);
            }
        });
        searchMenu.add(TheoGioiTinh);

        TheoQueQuan.setText("Theo quê quán");
        TheoQueQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TheoQueQuanActionPerformed(evt);
            }
        });
        searchMenu.add(TheoQueQuan);

        TheoLop.setText("Theo lớp");
        TheoLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TheoLopActionPerformed(evt);
            }
        });
        searchMenu.add(TheoLop);

        jMenu1.add(searchMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbQueQuan, javax.swing.GroupLayout.Alignment.LEADING, 0, 269, Short.MAX_VALUE)
                            .addComponent(tfHoTen, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(rbNam)
                                .addGap(48, 48, 48)
                                .addComponent(rbNu))
                            .addComponent(tfMSGV, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNgaySinh, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbLop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfMSGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbNam)
                            .addComponent(rbNu)
                            .addComponent(jLabel5)))
                    .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbLop, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNgaySinhActionPerformed

    private void tfHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHoTenActionPerformed

    public void resetForm(){
        tfHoTen.setText("");
        tfMSGV.setText("");
        cbLop.setSelectedIndex(0);
        rbNam.setSelected(true);
        imgLabel.setIcon(null);
        tfNgaySinh.setText("");
        cbQueQuan.setSelectedIndex(0);
        
    }
    
    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        if (tfNgaySinh.getText().equals("")||tfMSGV.getText().equals("")||tfHoTen.getText().equals("")||(rbNam.isSelected()==false&&rbNu.isSelected()==false)){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
        }
        else {
            try {
                GiaoVien gv = new GiaoVien(tfMSGV.getText(),tfHoTen.getText(),formatDate.parse(tfNgaySinh.getText()),rbNam.isSelected()?"Nam":"Nu",cbQueQuan.getSelectedItem().toString(),cbLop.getSelectedItem().toString(),imgURL);
                GiaoVienBUS hsBUS = new GiaoVienBUS();
                if (hsBUS.updateGiaoVien(gv)!=0) JOptionPane.showMessageDialog(this, "Sửa thành công");
                else JOptionPane.showMessageDialog(this, "Sửa không thành công");
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Ngày sinh không hợp lệ");
            }
            } 
        loadDataTable();
        resetForm();
    }//GEN-LAST:event_editBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        if (tfNgaySinh.getText().equals("")||tfMSGV.getText().equals("")||tfHoTen.getText().equals("")||(rbNam.isSelected()==false&&rbNu.isSelected()==false)){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
        }
        else {
            try {
                GiaoVien gv = new GiaoVien(tfMSGV.getText(),tfHoTen.getText(),formatDate.parse(tfNgaySinh.getText()),rbNam.isSelected()?"Nam":"Nu",cbQueQuan.getSelectedItem().toString(),cbLop.getSelectedItem().toString(),imgURL);
                GiaoVienBUS hsBUS = new GiaoVienBUS();
                if (hsBUS.addGiaoVien(gv)!=0) JOptionPane.showMessageDialog(this, "Thêm thành công");
                else JOptionPane.showMessageDialog(this, "Thêm không thành công");
                } catch (ParseException ex) {
                 JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng ngày sinh");
            }
        }    
        resetForm();
        loadDataTable();
    }//GEN-LAST:event_addBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // TODO add your handling code here:
        int i = tbDSGV.getSelectedRow();
        GiaoVienBUS gvBUS = new GiaoVienBUS();
        
        if (i>=0){
                if (gvBUS.deleteGiaoVien(model.getValueAt(i,1).toString())!=0) JOptionPane.showMessageDialog(this, "Xóa thành công");
                else JOptionPane.showMessageDialog(this, "Xóa không thành công");
        
        resetForm();
        loadDataTable();
        }
        else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn học sinh để xóa");
        }
    }//GEN-LAST:event_delBtnActionPerformed

        
    private void imgLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgLabelMouseClicked
        try {
            // TODO add your handling code here:
            JFileChooser jfc = new JFileChooser(directory.getAbsolutePath()+"//src//images");
            jfc.showOpenDialog(null);
            File file = jfc.getSelectedFile();
            imgURL=file.toString().replace(directory.getAbsolutePath(),"");
            Image img = ImageIO.read(file);
            int width = imgLabel.getWidth();
            int height = imgLabel.getHeight();
            imgLabel.setIcon(new ImageIcon(img.getScaledInstance(width, height-20,  Image.SCALE_SMOOTH)));
        } catch (IOException ex) {
            Logger.getLogger(QLHSView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_imgLabelMouseClicked

    private void cbQueQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQueQuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbQueQuanActionPerformed

    private void rbNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNamActionPerformed

    private void tbDSHSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDSHSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDSHSMouseClicked

    private void tbDSGVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDSGVMouseClicked
        // TODO add your handling code here:
               model = (DefaultTableModel)tbDSGV.getModel();
        int i = tbDSGV.getSelectedRow();
        if (i>=0){
            tfMSGV.setText(model.getValueAt(i,1).toString());
            tfHoTen.setText(model.getValueAt(i,2).toString());
            tfNgaySinh.setText(model.getValueAt(i,3).toString());
            if(model.getValueAt(i,4).toString().equals("Nam"))
                rbNam.setSelected(true); 
            else rbNu.setSelected(true);
            cbLop.setSelectedItem(model.getValueAt(i,5).toString());
            cbQueQuan.setSelectedItem(model.getValueAt(i,6).toString());           
            ImageIcon img = new ImageIcon(directory.getAbsolutePath()+dsgv.get(i).getImg());
            imgLabel.setIcon(new ImageIcon(img.getImage().getScaledInstance(imgLabel.getWidth()-10, imgLabel.getHeight()-20, Image.SCALE_SMOOTH)));

        }
    }//GEN-LAST:event_tbDSGVMouseClicked

    private void TheoLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheoLopActionPerformed
        // TODO add your handling code here:
        String s = (String)JOptionPane.showInputDialog(this,
                "Nhập lớp cần tìm",
                "Tìm kiếm theo lớp",
                JOptionPane.INFORMATION_MESSAGE);
        if (s.equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
        }
        else {
        Connection con;
        try{          
            con = DriverManager.getConnection(dbUrl,username,password);
            System.out.println("Connection successful");
            Statement st=con.createStatement();
            ResultSet rs =st.executeQuery("SELECT * FROM HOCSINH");
            model = (DefaultTableModel)tbDSGV.getModel();
            model.setRowCount(0); 
            int i=0;
            while(rs.next()){
                if (rs.getString(6).contains(s)){                      
                    model.addRow(new Object[]{i+1,rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(6),rs.getString(5)});
                    i++;
                }               
            }      
           con.close();
           JOptionPane.showMessageDialog(this, "Tìm kiếm thành công!");
        } catch(Exception e){
            System.out.println("Connect Error "+e);
        } 
        }
    }//GEN-LAST:event_TheoLopActionPerformed

    private void TheoMSGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheoMSGVActionPerformed
        // TODO add your handling code here:
        String s = (String)JOptionPane.showInputDialog(this,
                "Nhập MSSV cần tìm",
                "Tìm kiếm theo MSSV",
                JOptionPane.INFORMATION_MESSAGE);
        if (s.equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
        }
        else {
        Connection con;
        try{          
            con = DriverManager.getConnection(dbUrl,username,password);
            System.out.println("Connection successful");
            Statement st=con.createStatement();
            ResultSet rs =st.executeQuery("SELECT * FROM HOCSINH");
            model = (DefaultTableModel)tbDSGV.getModel();
            model.setRowCount(0); 
            int i=0;
            while(rs.next()){               
                if (rs.getString(1).contains(s)){                      
                    model.addRow(new Object[]{i+1,rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(6),rs.getString(5)});
                    i++;
                }               
            }      
           con.close();
           JOptionPane.showMessageDialog(this, "Tìm kiếm thành công!");
        } catch(Exception e){
            System.out.println("Connect Error "+e);
        } 
        }
    }//GEN-LAST:event_TheoMSGVActionPerformed

    private void TheoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheoTenActionPerformed
        // TODO add your handling code here:
        String s = (String)JOptionPane.showInputDialog(this,
                "Nhập họ tên cần tìm",
                "Tìm kiếm theo họ tên",
                JOptionPane.INFORMATION_MESSAGE);
        if (s.equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
        }
        else {
        Connection con;
        try{          
            con = DriverManager.getConnection(dbUrl,username,password);
            System.out.println("Connection successful");
            Statement st=con.createStatement();
            ResultSet rs =st.executeQuery("SELECT * FROM HOCSINH");
            model = (DefaultTableModel)tbDSGV.getModel();
            model.setRowCount(0); 
            int i=0;
            while(rs.next()){
                if (rs.getString(2).contains(s)){                      
                    model.addRow(new Object[]{i+1,rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(6),rs.getString(5)});
                    i++;
                }               
            }      
           con.close();
           JOptionPane.showMessageDialog(this, "Tìm kiếm thành công!");
        } catch(Exception e){
            System.out.println("Connect Error "+e);
        } 
        }
    }//GEN-LAST:event_TheoTenActionPerformed

    private void TheoNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheoNgaySinhActionPerformed
        // TODO add your handling code here:
        String s = (String)JOptionPane.showInputDialog(this,
                "Nhập ngày sinh cần tìm",
                "Tìm kiếm theo ngày sinh",
                JOptionPane.INFORMATION_MESSAGE);
        if (s.equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
        }
        else {
        Connection con;
        try{          
            con = DriverManager.getConnection(dbUrl,username,password);
            System.out.println("Connection successful");
            Statement st=con.createStatement();
            ResultSet rs =st.executeQuery("SELECT * FROM HOCSINH");
            model = (DefaultTableModel)tbDSGV.getModel();
            model.setRowCount(0); 
            int i=0;
            while(rs.next()){
                if (rs.getString(3).contains(s)){                      
                    model.addRow(new Object[]{i+1,rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(6),rs.getString(5)});
                    i++;
                }               
            }      
           con.close();
           JOptionPane.showMessageDialog(this, "Tìm kiếm thành công!");
        } catch(Exception e){
            System.out.println("Connect Error "+e);
        } 
        }
    }//GEN-LAST:event_TheoNgaySinhActionPerformed

    private void TheoGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheoGioiTinhActionPerformed
        // TODO add your handling code here:
        String s = (String)JOptionPane.showInputDialog(this,
                "Nhập giới tính cần tìm",
                "Tìm kiếm theo giới tính",
                JOptionPane.INFORMATION_MESSAGE);
        if (s.equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
        }
        else {
        Connection con;
        try{          
            con = DriverManager.getConnection(dbUrl,username,password);
            System.out.println("Connection successful");
            Statement st=con.createStatement();
            ResultSet rs =st.executeQuery("SELECT * FROM HOCSINH");
            model = (DefaultTableModel)tbDSGV.getModel();
            model.setRowCount(0); 
            int i=0;
            while(rs.next()){
                if (rs.getString(4).contains(s)){                      
                    model.addRow(new Object[]{i+1,rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(6),rs.getString(5)});
                    i++;
                }               
            }      
           con.close();
           JOptionPane.showMessageDialog(this, "Tìm kiếm thành công! ");
        } catch(Exception e){
            System.out.println("Connect Error "+e);
        } 
        }
    }//GEN-LAST:event_TheoGioiTinhActionPerformed

    private void TheoQueQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheoQueQuanActionPerformed
        // TODO add your handling code here:
        String s = (String)JOptionPane.showInputDialog(this,
                "Nhập quê quán cần tìm",
                "Tìm kiếm theo quê quán",
                JOptionPane.INFORMATION_MESSAGE);
        if (s.equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
        }
        else {
        Connection con;
        try{          
            con = DriverManager.getConnection(dbUrl,username,password);
            System.out.println("Connection successful");
            Statement st=con.createStatement();
            ResultSet rs =st.executeQuery("SELECT * FROM HOCSINH");
            model = (DefaultTableModel)tbDSGV.getModel();
            model.setRowCount(0); 
            int i=0;
            while(rs.next()){
                if (rs.getString(5).contains(s)){                      
                    model.addRow(new Object[]{i+1,rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(6),rs.getString(5)});
                    i++;
                }               
            }      
           con.close();
           JOptionPane.showMessageDialog(this, "Tìm kiếm thành công!");
        } catch(Exception e){
            System.out.println("Connect Error "+e);
        } 
        }
    }//GEN-LAST:event_TheoQueQuanActionPerformed

    private void RefreshMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshMenuActionPerformed
        // TODO add your handling code here:
        loadData();
        loadDataTable();
        resetForm();
    }//GEN-LAST:event_RefreshMenuActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        FrMainForm mainForm;
        mainForm = new FrMainForm();
        mainForm.setVisible(true);
        mainForm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

                             


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLGVView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLGVView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLGVView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLGVView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLGVView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem RefreshMenu;
    private javax.swing.JMenuItem TheoGioiTinh;
    private javax.swing.JMenuItem TheoLop;
    private javax.swing.JMenuItem TheoMSGV;
    private javax.swing.JMenuItem TheoNgaySinh;
    private javax.swing.JMenuItem TheoQueQuan;
    private javax.swing.JMenuItem TheoTen;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel background;
    private javax.swing.JPanel background1;
    private javax.swing.JPanel background2;
    private javax.swing.JPanel background3;
    private javax.swing.JPanel background4;
    private javax.swing.JPanel background5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbLop;
    private javax.swing.JComboBox<String> cbQueQuan;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton rbNam;
    private javax.swing.JRadioButton rbNu;
    private javax.swing.JMenu searchMenu;
    private javax.swing.JTable tbDSGV;
    private javax.swing.JTable tbDSHS;
    private javax.swing.JTextField tfHoTen;
    private javax.swing.JTextField tfMSGV;
    private javax.swing.JTextField tfNgaySinh;
    // End of variables declaration//GEN-END:variables
}