/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.LopHocBUS;
import DTO.HocSinh;
import DTO.LopHoc;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tit
 */
public class QLLOPView extends javax.swing.JFrame {

    /**
     * Creates new form QLLOPView
     */
    ArrayList<LopHoc> dslh = new ArrayList<>();
    DefaultTableModel model ;
    SimpleDateFormat formatDate = new SimpleDateFormat("dd/MM/yyyy");
    public void loadData(){
        try{   
            dslh.clear();
            LopHocBUS lhBUS = new LopHocBUS();
            dslh = lhBUS.getAllLopHoc();
        } catch(Exception e){
            System.out.println("Connect Error "+e);
        } 
    }
    public void loadDataTable(){   
        loadData();
        model = (DefaultTableModel)tbLop.getModel();
        model.setRowCount(0);
        for (int i=0;i<dslh.size();i++){
            model.addRow(new Object[]{dslh.get(i).getMaLop(),dslh.get(i).getTenLop()});       
        }
                  
    }
    public QLLOPView() {
        initComponents();
        loadDataTable();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLop = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbHocSinh = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tfMSLop = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfTenLop = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        siso = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ LỚP HỌC");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("QUẢN LÝ LỚP HỌC");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 22, 215, 46));

        tbLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "MaLop", "TenLop"
            }
        ));
        tbLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLopMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLop);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 160, 117));

        tbHocSinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MSHS", "Họ và Tên", "Giới tính", "Ngày sinh"
            }
        ));
        jScrollPane2.setViewportView(tbHocSinh);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 540, 117));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã Lớp :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 82, 28));

        tfMSLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMSLopActionPerformed(evt);
            }
        });
        getContentPane().add(tfMSLop, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 191, 28));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tên Lớp :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 168, 82, 28));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tổng số học sinh :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, 26));
        getContentPane().add(tfTenLop, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 168, 191, 28));

        addBtn.setBackground(new java.awt.Color(255, 255, 255));
        addBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addBtn.setText("THÊM");
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.setPreferredSize(new java.awt.Dimension(70, 35));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 110, 36));

        delBtn.setBackground(new java.awt.Color(255, 255, 255));
        delBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        delBtn.setText("XÓA");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });
        getContentPane().add(delBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 107, 36));

        editBtn.setBackground(new java.awt.Color(255, 255, 255));
        editBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        editBtn.setText("SỬA");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        getContentPane().add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 110, 36));

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        backBtn.setText("QUAY LẠI");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 230, 109, 36));

        siso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        siso.setText("0");
        getContentPane().add(siso, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 40, 26));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lop2.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 730, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        if (tfMSLop.getText().equals("")&&tfTenLop.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
        }
        else {
            LopHoc lh = new LopHoc(tfMSLop.getText(), tfTenLop.getText());
            LopHocBUS lhBUS = new LopHocBUS();
            if (lhBUS.addLopHoc(lh)!=0) JOptionPane.showMessageDialog(this, "Thêm thành công");
                else JOptionPane.showMessageDialog(this, "Thêm không thành công");
        }
        loadDataTable();
    }//GEN-LAST:event_addBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // TODO add your handling code here:
        int i = tbLop.getSelectedRow();
        LopHocBUS lhBUS = new LopHocBUS();
        if (i>=0){
            LopHoc lh = new LopHoc(tfMSLop.getText(), tfTenLop.getText());
            int j =lhBUS.delLopHoc(lh);
            if (j!=0) JOptionPane.showMessageDialog(this, "Xóa thành công "+j);
                else JOptionPane.showMessageDialog(this, "Xóa không thành công "+j);
        
        }
        else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn lớp để xóa");
        }
        loadDataTable();
    }//GEN-LAST:event_delBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:

     
        LopHocBUS lhBUS = new LopHocBUS();
        int i = tbLop.getSelectedRow();
        if (i>=0){
            if (tfMSLop.getText().equals("")&&tfTenLop.getText().equals("")){JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");}
            else {
                int qes=JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn? Tất cả học sinh sẽ được thay đổi sang lớp mới", "Question",JOptionPane.YES_NO_OPTION);
                if(qes==JOptionPane.YES_OPTION){
                    LopHoc lh = new LopHoc(tfMSLop.getText(), tfTenLop.getText());
                    int j =lhBUS.updateLopHoc(lh,model.getValueAt(i, 1).toString());
                    System.out.println(model.getValueAt(i, 1).toString());
                    if (j!=0) JOptionPane.showMessageDialog(this, "Sửa thành công");
                    else JOptionPane.showMessageDialog(this, "Sửa không thành công");
                }
                else return;
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn lớp để sửa");
        }
       
    }//GEN-LAST:event_editBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        FrMainForm mainForm;
        mainForm = new FrMainForm();
        mainForm.setVisible(true);
        mainForm.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_backBtnActionPerformed

    private void tbLopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLopMouseClicked
        // TODO add your handling code here:
         model = (DefaultTableModel)tbLop.getModel();
        int i = tbLop.getSelectedRow();
        if (i>=0){
            tfMSLop.setText(model.getValueAt(i, 0).toString());
            tfTenLop.setText(model.getValueAt(i, 1).toString());
            DefaultTableModel model1 = (DefaultTableModel)tbHocSinh.getModel();
            ArrayList<HocSinh> dshs = new ArrayList<>();
            LopHocBUS lhBUS = new LopHocBUS();
            dshs = lhBUS.getAllHocSinh(model.getValueAt(i, 1).toString());
            model1.setRowCount(0);
            for (int j=0;j<dshs.size();j++){
            model1.addRow(new Object[]{dshs.get(j).getMSHS(),dshs.get(j).getHoTen(),dshs.get(j).getGioiTinh(),formatDate.format(dshs.get(j).getNgaySinh())});       
        }   siso.setText(String.valueOf(dshs.size()));
            
        }
    }//GEN-LAST:event_tbLopMouseClicked

    private void tfMSLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMSLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMSLopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLLOPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLLOPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLLOPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLLOPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display tbLopm */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLLOPView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel siso;
    private javax.swing.JTable tbHocSinh;
    private javax.swing.JTable tbLop;
    private javax.swing.JTextField tfMSLop;
    private javax.swing.JTextField tfTenLop;
    // End of variables declaration//GEN-END:variables
}