/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.UserBUS;
import DTO.UserDTO;
import static java.awt.Color.BLACK;
import static java.awt.Color.GRAY;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tit
 */
public class UserGUI extends javax.swing.JFrame {

    /**
     * Creates new form QLUserView
     */
    ArrayList<UserDTO> dsUser = new ArrayList<>();
    DefaultTableModel model;
    void loadDataTable(){
        
        UserBUS userBUS = new UserBUS();
        dsUser = userBUS.getAllUser();
        model = (DefaultTableModel) tbUsers.getModel();
        model.setRowCount(0);
        for (int i = 0; i < dsUser.size(); i++) {
            model.addRow(new Object[]{dsUser.get(i).getUserName()});
           
        }  
    }
    
        
        
    public UserGUI() {
        initComponents();
        btnAdd.setIcon(new ImageIcon(new ImageIcon("src//images//plus.png").getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
        btnDel.setIcon(new ImageIcon(new ImageIcon("src//images//delete.png").getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
        btnEdit.setIcon(new ImageIcon(new ImageIcon("src//images//edit.png").getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
        btnBack.setIcon(new ImageIcon(new ImageIcon("src//images//previous.png").getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
        btnSearch.setIcon(new ImageIcon(new ImageIcon("src//images//search.png").getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH)));
        btnClear.setIcon(new ImageIcon(new ImageIcon("src//images//cleaning.png").getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
        JLabel background = new JLabel();
        background.setBounds(0, 0, this.getWidth(), this.getHeight());
        background.setIcon(new ImageIcon(new ImageIcon("src//images//backgroundQLUser.jpg").getImage().getScaledInstance(background.getWidth(), background.getHeight(), Image.SCALE_SMOOTH)));
        this.add(background);

        loadDataTable();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rdStandard = new javax.swing.JRadioButton();
        rdAdmin = new javax.swing.JRadioButton();
        tfUser = new javax.swing.JTextField();
        tfPass = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsers = new javax.swing.JTable();
        tfSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 460));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("   QUẢN LÝ TÀI KHOẢN ");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(182, 21, 276, 51);

        jLabel2.setText("USERNAME :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(237, 103, 99, 26);

        jLabel3.setText("PASSWORD :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(237, 170, 99, 25);

        jLabel4.setText("ACCOUNT TYPE :  ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(237, 233, 122, 24);

        buttonGroup1.add(rdStandard);
        rdStandard.setText("Standard");
        rdStandard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdStandardActionPerformed(evt);
            }
        });
        getContentPane().add(rdStandard);
        rdStandard.setBounds(510, 230, 100, 23);

        buttonGroup1.add(rdAdmin);
        rdAdmin.setText(" Administrator");
        rdAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAdminActionPerformed(evt);
            }
        });
        getContentPane().add(rdAdmin);
        rdAdmin.setBounds(370, 230, 120, 23);
        getContentPane().add(tfUser);
        tfUser.setBounds(369, 103, 190, 26);
        getContentPane().add(tfPass);
        tfPass.setBounds(369, 170, 190, 25);

        tbUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "USER LIST"
            }
        ));
        tbUsers.setGridColor(new java.awt.Color(153, 0, 153));
        tbUsers.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tbUsers.setSelectionForeground(new java.awt.Color(255, 204, 0));
        tbUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbUsers);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(33, 103, 169, 237);

        tfSearch.setForeground(java.awt.Color.gray);
        tfSearch.setText("Search");
        tfSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfSearchFocusLost(evt);
            }
        });
        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });
        getContentPane().add(tfSearch);
        tfSearch.setBounds(33, 358, 130, 27);

        btnSearch.setBackground(new java.awt.Color(255, 204, 153));
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch);
        btnSearch.setBounds(169, 358, 33, 27);

        btnAdd.setBackground(new java.awt.Color(255, 204, 153));
        btnAdd.setText("THÊM");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(237, 302, 111, 33);

        btnEdit.setBackground(new java.awt.Color(255, 204, 153));
        btnEdit.setText("SỬA");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit);
        btnEdit.setBounds(496, 302, 111, 33);

        btnDel.setBackground(new java.awt.Color(255, 204, 153));
        btnDel.setText("XÓA");
        btnDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        getContentPane().add(btnDel);
        btnDel.setBounds(366, 302, 112, 33);

        btnBack.setBackground(new java.awt.Color(255, 204, 153));
        btnBack.setText("QUAY LẠI");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(366, 353, 111, 33);

        btnClear.setBackground(new java.awt.Color(255, 204, 153));
        btnClear.setText("CLEAR");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(237, 353, 111, 33);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdStandardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdStandardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdStandardActionPerformed

    private void tbUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsersMouseClicked
        // TODO add your handling code here:
        model = (DefaultTableModel) tbUsers.getModel();
        int i = tbUsers.getSelectedRow();
        for (UserDTO u : dsUser){
            if (u.getUserName().equals(model.getValueAt(i,0))) {
                tfUser.setText(u.getUserName());
                tfPass.setText(u.getPassWord());
                if (u.getLevel() == 0) rdAdmin.setSelected(true); else rdStandard.setSelected(true);
                break;
            }
        }
    }//GEN-LAST:event_tbUsersMouseClicked
    void resetForm(){
        tfUser.setText("");
        tfPass.setText("");
        rdAdmin.setSelected(false);
        rdStandard.setSelected(false);
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (tfPass.getText().equals("")||tfUser.getText().equals("")||(rdAdmin.isSelected() == false && rdStandard.isSelected() == false)) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
        } else {
            for (UserDTO u : dsUser) if (u.getUserName().equals(tfUser.getText())) {
                JOptionPane.showMessageDialog(this, "Tài khoản "+tfUser.getText()+" đã tồn tại !");
                return;
            }
                UserDTO us = new UserDTO(tfUser.getText(),tfPass.getText(),rdAdmin.isSelected() ? 0:1);
                UserBUS hsBUS = new UserBUS();
                if (hsBUS.addUser(us) != 0) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm không thành công");
                }
        }
        resetForm();
        loadDataTable();

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        int i = tbUsers.getSelectedRow();
         UserBUS usBUS = new UserBUS();

        if (i >= 0) {
            if (usBUS.delUser(model.getValueAt(i, 0).toString()) != 0) {
                JOptionPane.showMessageDialog(this, "Xóa thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Xóa không thành công");
            }

            resetForm();
            loadDataTable();
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tài khoản để xóa");
        }
        
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        HomeGUI mainForm;
        mainForm = new HomeGUI();
        mainForm.setVisible(true);
        mainForm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int i = tbUsers.getSelectedRow();
        UserBUS usBUS = new UserBUS();
        if (tfPass.getText().equals("")||tfUser.getText().equals("")||(rdAdmin.isSelected() == false && rdStandard.isSelected() == false)) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");return;}
        
        if (i >= 0) {
            UserDTO us = new UserDTO(tfUser.getText(),tfPass.getText(),rdAdmin.isSelected() ? 0:1);
            if (usBUS.delUser(model.getValueAt(i, 0).toString())!=0&&usBUS.addUser(us)!=0){
                JOptionPane.showMessageDialog(this, "Sửa thành công");
            }
            else JOptionPane.showMessageDialog(this, "Sửa không thành công");
            resetForm();
            loadDataTable();
        }
        else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tài khoản để sửa");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void tfSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSearchFocusGained
        // TODO add your handling code here
        if (tfSearch.getText().equals("Search")) {
            tfSearch.setText("");
            tfSearch.setForeground(BLACK);
        }
    }//GEN-LAST:event_tfSearchFocusGained

    private void tfSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSearchFocusLost
        // TODO add your handling code here:
        if (tfSearch.getText().isEmpty()) {
            tfSearch.setForeground(GRAY);
            tfSearch.setText("Search");
        }
    }//GEN-LAST:event_tfSearchFocusLost

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        UserBUS usBUS = new UserBUS();
        ArrayList<UserDTO> Users = usBUS.search(tfSearch.getText());
        model = (DefaultTableModel) tbUsers.getModel();
        model.setRowCount(0);
        for (int i = 0; i < Users.size(); i++) {
            model.addRow(new Object[]{Users.get(i).getUserName()});
            }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        resetForm();
        loadDataTable();
    }//GEN-LAST:event_btnClearActionPerformed

    private void rdAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdAdmin;
    private javax.swing.JRadioButton rdStandard;
    private javax.swing.JTable tbUsers;
    private javax.swing.JTextField tfPass;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}